import { error } from '@sveltejs/kit';
import { Avatars, Client } from 'node-appwrite';
import type { RequestHandler } from './$types';
import { DATABASE_ID, ENDPOINT, PROJECT_ID } from '$lib/server/appwrite';
import { requireUser } from '$lib/server/auth';
import { notFoundOnFailure } from '$lib/server/errors';
import { formsCollection } from '$lib/server/tenant';

/**
 * Serves a QR code for the form's public link. Membership is checked by reading the form with the
 * member's session. The image is generated by the backend's avatars endpoint, which is open to
 * guests (no API key or extra scope needed), and proxied so it can be downloaded from the app's own
 * origin.
 */
export const GET: RequestHandler = async (event) => {
	const { appwrite } = requireUser(event);
	const { team: teamId, formId } = event.params;

	let title = 'form';
	try {
		const form = await appwrite.db.getDocument({
			databaseId: DATABASE_ID,
			collectionId: formsCollection(teamId),
			documentId: formId
		});
		title = String(form.title ?? title);
	} catch (err) {
		notFoundOnFailure(err, 'Form not found');
	}

	let png: ArrayBuffer;
	try {
		const guest = new Client().setEndpoint(ENDPOINT).setProject(PROJECT_ID);
		png = await new Avatars(guest).getQR({
			text: `${event.url.origin}/f/${teamId}/${formId}`,
			size: 480,
			margin: 1
		});
	} catch {
		error(502, 'Could not generate the QR code. Please try again.');
	}

	const download = event.url.searchParams.get('download') === '1';
	const filename = `${title.replace(/[^\w.-]+/g, '_') || 'form'}-qr.png`;
	return new Response(png, {
		headers: {
			'content-type': 'image/png',
			'content-length': String(png.byteLength),
			'content-disposition': `${download ? 'attachment' : 'inline'}; filename="${filename}"`,
			'cache-control': 'private, max-age=300'
		}
	});
};
